### ISSUE TITLE
使用web-ui修改pix参数后pix插件就用不了了

### ISSUE THREAD

**Issue by jk6589jk** [HibiKier/zhenxun_bot#546]
使用web-ui修改pix的配置项之后
```
pix:
  # PIX图库
  # PIX_IMAGE_SIZE: PIX图库下载的画质 可能的值：original：原图，master：缩略图（加快发送速度）
  # SEARCH_HIBIAPI_BOOKMARKS: 最低收藏，PIX使用HIBIAPI搜索图片时达到最低收藏才会添加至图库
  # WITHDRAW_PIX_MESSAGE: 自动撤回，参1：延迟撤回色图时间(秒)，0 为关闭 | 参2：监控聊天类型，0(私聊) 1(群聊) 2(群聊+私聊)
  # PIX_OMEGA_PIXIV_RATIO: PIX图库 与 额外图库OmegaPixivIllusts 混合搜索的比例 参1：PIX图库 参2：OmegaPixivIllusts扩展图库（没有此图库请设置为0）
  # TIMEOUT: 下载图片超时限制（秒）
  # SHOW_INFO: 是否显示图片的基本信息，如PID等
  # MAX_ONCE_NUM2FORWARD: 单次发送的图片数量达到指定值时转发为合并消息
  PIX_IMAGE_SIZE:
  - master
  SEARCH_HIBIAPI_BOOKMARKS: 500
  WITHDRAW_PIX_MESSAGE:
  - '0'
  - '1'
  PIX_OMEGA_PIXIV_RATIO:
  - '10'
  - '0'
  TIMEOUT: 20
  SHOW_INFO: true
  MAX_ONCE_NUM2FORWARD: 'null'
```
在config.yaml里面配置变成这样了，使用pix指令的时候会报错
 ```
 File "/root/mahiro/zhenxun_bot-0.1.5.3/plugins/pix_gallery/pix.py", line 68, in _
    PIX_RATIO = pix_omega_pixiv_ratio[0] / (
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

然后我把PIX_OMEGA_PIXIV_RATIO和MAX_ONCE_NUM2FORWARD改成数值型和null之后就恢复正常了，但是用web-ui改还是会变成字符型。
